### PR TITLE
User guide patch

### PR DESCRIPTION
**Pull request by Jeremylsw**

### CODE REVIEW

**Comment by Jeremylsw** [comment]
@rushan-khor @ErnestOYH

Refer to the links provided on old and new user guide and give at least 1 criticism each on how the user guide can be improved.

Link to new user guide
https://github.com/Jeremylsw/MedNus/blob/2101UserGuide/docs/UserGuide.adoc#keyboard-shortcut

Link to old user guide
https://github.com/Jeremylsw/MedNus/blob/master/docs/UserGuide.adoc

**Comment by Jeremylsw** [comment]
Comments By @EricLoh 
Can have a short description before every table.

E.g. Commands table, Keyboard short cut table

**Comment by ErnestOYH** [comment]
Perhaps the examples for different features can be in table format as well.

Some of the features are implemented in the current v1.2 build and can be updated accordingly.
Set Appointment and Deleting all persons with a particular tag.

**Comment by rushan-khor** [comment]
Looks good. Perhaps we can add a link to the Java 8 download page in
• "Make sure you have Java version 1.8.0_60 or later installed in your Computer."

**Pull request merged**
