### PR TITLE
Developer guide ravamp

### PR DESCRIPTION
**Pull request by rushan-khor**

### CODE REVIEW

**Comment by rushan-khor** [comment]
@EricLoh 
You may view this from my own repo's [dev guide](https://github.com/rushan-khor/addressbook-level4/blob/developer-guide-ravamp/docs/DeveloperGuide.adoc).

**Comment by EricLoh** [comment]
Reviewed. 
Will merge after Jeremy and Ernest give their comments.

**Comment by Jeremylsw** [comment]
Save the 2103 stuff somewhere - User stories etc, Wk9 dev guide appendixes and check with Brandon if we still need them for 2103 evaluation.
Merge when 2103 information isolated, convert to pdf and upload to IVLE forum

**Comment by rushan-khor** [comment]
Thanks for the feedback. You can view the latest rendition [right here](https://github.com/rushan-khor/addressbook-level4/blob/developer-guide-ravamp/docs/DeveloperGuide.adoc).

**Latest rendition has these changes:**
• Added back the full, comprehensive content from our old "2103 Developer Guide".
• However, used the concise writing style of the new "2101 Developer Guide"
• This version is ready for submission, but we may choose to trim content further

**Pull request merged**
